(* JH7110/CoreSmokePass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [core_smoke] on platform [jh7110].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.JH7110 Require Import CoreSmokeRun.

Module CoreSmokePass <: TEST_PASSES CoreSmoke.
  Lemma passes : run_passes CoreSmoke.observed CoreSmoke.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End CoreSmokePass.
