(* JH7110/CoreRegsGprPass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [core_regs_gpr] on platform [jh7110].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.JH7110 Require Import CoreRegsGprRun.

Module CoreRegsGprPass <: TEST_PASSES CoreRegsGpr.
  Lemma passes : run_passes CoreRegsGpr.observed CoreRegsGpr.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End CoreRegsGprPass.
