(* CodeAllocproc.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's allocproc: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [api_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode00.
Require Import KernelDecode01.
Require Import KernelDecode02.
Require Import KernelDecode03.
Require Import KernelDecode04.
Require Import KernelDecode05.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode08.
Require Import KernelDecode09.
Require Import KernelDecode10.
Require Import KernelDecode12.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode19.
Require Import KernelDecode20.
Require Import KernelDecode21.
Require Import KernelDecode22.
Require Import KernelDecode23.
Require Import KernelDecode24.
Require Import KernelDecode25.
Require Import KernelDecode26.
Require Import KernelDecode28.
Require Import KernelDecode29.
Require Import KernelDecode30.
Local Open Scope Z_scope.
Import Defs.


Section CodeAllocproc.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- allocproc @ KernelSyms.allocproc, 166 bytes ---- *)

  Lemma api_00 : kernel_text -∗ instr (mword_of_int KernelSyms.allocproc : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof. mk_rvc KernelSyms.allocproc (mword_of_int 0x1101 : mword 16)
    (mword_of_int KernelSyms.allocproc : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1101 exec_execute_C_ADDI. Qed.

  Lemma api_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x2) (mword_of_int 0xec06 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_ec06 exec_execute_C_SDSP. Qed.

  Lemma api_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x4) (mword_of_int 0xe822 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e822 exec_execute_C_SDSP. Qed.

  Lemma api_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x6) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x6) (mword_of_int 0xe426 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x6) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)) kd_e426 exec_execute_C_SDSP. Qed.

  Lemma api_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x8) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x8) (mword_of_int 0xe04a : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x8) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)) kd_e04a exec_execute_C_SDSP. Qed.

  Lemma api_0a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0xa) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0xa) (mword_of_int 0x1000 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0xa) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1000 exec_execute_C_ADDI4SPN. Qed.

  Lemma api_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0xc) : mword 64) false (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 9), AUIPC)).
  Proof. mk_base (KernelSyms.allocproc + 0xc) (mword_of_int 0x00011497 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0xc) : mword 64) (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 9), AUIPC)) kd_00011497. Qed.

  Lemma api_10 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x10) : mword 64) false (ITYPE (mword_of_int 3248 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x10) (mword_of_int 0xcb048493 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x10) : mword 64) (ITYPE (mword_of_int 3248 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)) kd_cb048493. Qed.

  Lemma api_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x14) : mword 64) false (UTYPE (mword_of_int 22 : mword 20, Regidx (mword_of_int 18), AUIPC)).
  Proof. mk_base (KernelSyms.allocproc + 0x14) (mword_of_int 0x00016917 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x14) : mword 64) (UTYPE (mword_of_int 22 : mword 20, Regidx (mword_of_int 18), AUIPC)) kd_00016917. Qed.

  Lemma api_18 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x18) : mword 64) false (ITYPE (mword_of_int 1704 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 18), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x18) (mword_of_int 0x6a890913 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x18) : mword 64) (ITYPE (mword_of_int 1704 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 18), ADDI)) kd_6a890913. Qed.

  Lemma api_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x1c) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x1c) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x1c) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x1e) : mword 64) false (JAL (mword_of_int 2093206 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x1e) (mword_of_int 0x896ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x1e) : mword 64) (JAL (mword_of_int 2093206 : mword 21, Regidx (mword_of_int 1))) kd_896ff0ef. Qed.

  Lemma api_22 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x22) : mword 64) true (LOAD (mword_of_int 24 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x22) (mword_of_int 0x4c9c : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x22) : mword 64) (LOAD (mword_of_int 24 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_4c9c ke_4c9c. Qed.

  Lemma api_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x24) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 10 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x24) (mword_of_int 0xcb91 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x24) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 10 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)) kd_cb91 exec_execute_C_BEQZ. Qed.

  Lemma api_26 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x26) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x26) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x26) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_28 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x28) : mword 64) false (JAL (mword_of_int 2093332 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x28) (mword_of_int 0x914ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x28) : mword 64) (JAL (mword_of_int 2093332 : mword 21, Regidx (mword_of_int 1))) kd_914ff0ef. Qed.

  Lemma api_2c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x2c) : mword 64) false (ITYPE (mword_of_int 360 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x2c) (mword_of_int 0x16848493 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x2c) : mword 64) (ITYPE (mword_of_int 360 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)) kd_16848493. Qed.

  Lemma api_30 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x30) : mword 64) false (BTYPE (mword_of_int 8172 : mword 13, Regidx (mword_of_int 18), Regidx (mword_of_int 9), BNE)).
  Proof. mk_base (KernelSyms.allocproc + 0x30) (mword_of_int 0xff2496e3 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x30) : mword 64) (BTYPE (mword_of_int 8172 : mword 13, Regidx (mword_of_int 18), Regidx (mword_of_int 9), BNE)) kd_ff2496e3. Qed.

  Lemma api_34 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x34) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 9), ADDI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x34) (mword_of_int 0x4481 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x34) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 9), ADDI)) kd_4481 exec_execute_C_LI. Qed.

  Lemma api_36 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x36) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 33 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x36) (mword_of_int 0xa089 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x36) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 33 : mword 11) ('b"0")), zreg)) kd_a089 exec_execute_C_J. Qed.

  Lemma api_38 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x38) : mword 64) false (JAL (mword_of_int 2096756 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x38) (mword_of_int 0xe75ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x38) : mword 64) (JAL (mword_of_int 2096756 : mword 21, Regidx (mword_of_int 1))) kd_e75ff0ef. Qed.

  Lemma api_3c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x3c) : mword 64) true (STORE (mword_of_int 48 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 4)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x3c) (mword_of_int 0xd888 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x3c) : mword 64) (STORE (mword_of_int 48 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 4)) kd_d888 ke_d888. Qed.

  Lemma api_3e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x3e) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x3e) (mword_of_int 0x4785 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x3e) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)) kd_4785 exec_execute_C_LI. Qed.

  Lemma api_40 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x40) : mword 64) true (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x40) (mword_of_int 0xcc9c : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x40) : mword 64) (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)) kd_cc9c ke_cc9c. Qed.

  Lemma api_42 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x42) : mword 64) false (JAL (mword_of_int 2092952 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x42) (mword_of_int 0xf99fe0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x42) : mword 64) (JAL (mword_of_int 2092952 : mword 21, Regidx (mword_of_int 1))) kd_f99fe0ef. Qed.

  Lemma api_46 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x46) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x46) (mword_of_int 0x892a : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x46) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)) kd_892a exec_execute_C_MV. Qed.

  Lemma api_48 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x48) : mword 64) true (STORE (mword_of_int 88 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x48) (mword_of_int 0xeca8 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x48) : mword 64) (STORE (mword_of_int 88 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 8)) kd_eca8 ke_eca8. Qed.

  Lemma api_4a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x4a) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 30 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x4a) (mword_of_int 0xcd15 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x4a) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 30 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)) kd_cd15 exec_execute_C_BEQZ. Qed.

  Lemma api_4c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x4c) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x4c) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x4c) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_4e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x4e) : mword 64) false (JAL (mword_of_int 2096796 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x4e) (mword_of_int 0xe9dff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x4e) : mword 64) (JAL (mword_of_int 2096796 : mword 21, Regidx (mword_of_int 1))) kd_e9dff0ef. Qed.

  Lemma api_52 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x52) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x52) (mword_of_int 0x892a : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x52) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)) kd_892a exec_execute_C_MV. Qed.

  Lemma api_54 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x54) : mword 64) true (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x54) (mword_of_int 0xe8a8 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x54) : mword 64) (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 8)) kd_e8a8 ke_e8a8. Qed.

  Lemma api_56 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x56) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 32 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x56) (mword_of_int 0xc121 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x56) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 32 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)) kd_c121 exec_execute_C_BEQZ. Qed.

  Lemma api_58 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x58) : mword 64) false (ITYPE (mword_of_int 112 : mword 12, zreg, Regidx (mword_of_int 12), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x58) (mword_of_int 0x07000613 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x58) : mword 64) (ITYPE (mword_of_int 112 : mword 12, zreg, Regidx (mword_of_int 12), ADDI)) kd_07000613. Qed.

  Lemma api_5c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x5c) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 11), ADDI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x5c) (mword_of_int 0x4581 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x5c) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 11), ADDI)) kd_4581 exec_execute_C_LI. Qed.

  Lemma api_5e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x5e) : mword 64) false (ITYPE (mword_of_int 96 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x5e) (mword_of_int 0x06048513 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x5e) : mword 64) (ITYPE (mword_of_int 96 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ADDI)) kd_06048513. Qed.

  Lemma api_62 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x62) : mword 64) false (JAL (mword_of_int 2093330 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x62) (mword_of_int 0x912ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x62) : mword 64) (JAL (mword_of_int 2093330 : mword 21, Regidx (mword_of_int 1))) kd_912ff0ef. Qed.

  Lemma api_66 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x66) : mword 64) false (UTYPE (mword_of_int 0 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof. mk_base (KernelSyms.allocproc + 0x66) (mword_of_int 0x00000797 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x66) : mword 64) (UTYPE (mword_of_int 0 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_00000797. Qed.

  Lemma api_6a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x6a) : mword 64) false (ITYPE (mword_of_int 3488 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof. mk_base (KernelSyms.allocproc + 0x6a) (mword_of_int 0xda078793 : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x6a) : mword 64) (ITYPE (mword_of_int 3488 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_da078793. Qed.

  Lemma api_6e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x6e) : mword 64) true (STORE (mword_of_int 96 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x6e) (mword_of_int 0xf0bc : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x6e) : mword 64) (STORE (mword_of_int 96 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 8)) kd_f0bc ke_f0bc. Qed.

  Lemma api_70 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x70) : mword 64) true (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x70) (mword_of_int 0x60bc : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x70) : mword 64) (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 8)) kd_60bc ke_60bc. Qed.

  Lemma api_72 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x72) : mword 64) true (UTYPE (sign_extend' 20 (mword_of_int 1 : mword 6), Regidx (mword_of_int 14), LUI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x72) (mword_of_int 0x6705 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x72) : mword 64) (UTYPE (sign_extend' 20 (mword_of_int 1 : mword 6), Regidx (mword_of_int 14), LUI)) kd_6705 exec_execute_C_LUI. Qed.

  Lemma api_74 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x74) : mword 64) true (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x74) (mword_of_int 0x97ba : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x74) : mword 64) (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADD)) kd_97ba exec_execute_C_ADD. Qed.

  Lemma api_76 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x76) : mword 64) true (STORE (mword_of_int 104 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x76) (mword_of_int 0xf4bc : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x76) : mword 64) (STORE (mword_of_int 104 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 8)) kd_f4bc ke_f4bc. Qed.

  Lemma api_78 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x78) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x78) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x78) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_7a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x7a) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x7a) (mword_of_int 0x60e2 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x7a) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60e2 exec_execute_C_LDSP. Qed.

  Lemma api_7c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x7c) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x7c) (mword_of_int 0x6442 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x7c) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6442 exec_execute_C_LDSP. Qed.

  Lemma api_7e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x7e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x7e) (mword_of_int 0x64a2 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x7e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)) kd_64a2 exec_execute_C_LDSP. Qed.

  Lemma api_80 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x80) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x80) (mword_of_int 0x6902 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x80) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6902 exec_execute_C_LDSP. Qed.

  Lemma api_82 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x82) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x82) (mword_of_int 0x6105 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x82) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)) kd_6105 exec_execute_C_ADDI16SP. Qed.

  Lemma api_84 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x84) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x84) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x84) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

  Lemma api_86 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x86) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x86) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x86) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_88 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x88) : mword 64) false (JAL (mword_of_int 2096940 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x88) (mword_of_int 0xf2dff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x88) : mword 64) (JAL (mword_of_int 2096940 : mword 21, Regidx (mword_of_int 1))) kd_f2dff0ef. Qed.

  Lemma api_8c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x8c) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x8c) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x8c) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_8e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x8e) : mword 64) false (JAL (mword_of_int 2093230 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x8e) (mword_of_int 0x8aeff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x8e) : mword 64) (JAL (mword_of_int 2093230 : mword 21, Regidx (mword_of_int 1))) kd_8aeff0ef. Qed.

  Lemma api_92 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x92) : mword 64) true (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 9), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x92) (mword_of_int 0x84ca : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x92) : mword 64) (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 9), ADD)) kd_84ca exec_execute_C_MV. Qed.

  Lemma api_94 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x94) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 2034 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x94) (mword_of_int 0xb7d5 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x94) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 2034 : mword 11) ('b"0")), zreg)) kd_b7d5 exec_execute_C_J. Qed.

  Lemma api_96 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x96) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x96) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x96) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_98 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x98) : mword 64) false (JAL (mword_of_int 2096924 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x98) (mword_of_int 0xf1dff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x98) : mword 64) (JAL (mword_of_int 2096924 : mword 21, Regidx (mword_of_int 1))) kd_f1dff0ef. Qed.

  Lemma api_9c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x9c) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0x9c) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0x9c) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma api_9e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0x9e) : mword 64) false (JAL (mword_of_int 2093214 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocproc + 0x9e) (mword_of_int 0x89eff0ef : mword 32)
    (mword_of_int (KernelSyms.allocproc + 0x9e) : mword 64) (JAL (mword_of_int 2093214 : mword 21, Regidx (mword_of_int 1))) kd_89eff0ef. Qed.

  Lemma api_a2 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0xa2) : mword 64) true (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 9), ADD)).
  Proof. mk_rvc (KernelSyms.allocproc + 0xa2) (mword_of_int 0x84ca : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0xa2) : mword 64) (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 9), ADD)) kd_84ca exec_execute_C_MV. Qed.

  Lemma api_a4 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocproc + 0xa4) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 2026 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.allocproc + 0xa4) (mword_of_int 0xbfd1 : mword 16)
    (mword_of_int (KernelSyms.allocproc + 0xa4) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 2026 : mword 11) ('b"0")), zreg)) kd_bfd1 exec_execute_C_J. Qed.

End CodeAllocproc.
