(* CodeConsoleintr.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's consoleintr: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [cnti_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode00.
Require Import KernelDecode01.
Require Import KernelDecode02.
Require Import KernelDecode03.
Require Import KernelDecode04.
Require Import KernelDecode05.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode08.
Require Import KernelDecode09.
Require Import KernelDecode10.
Require Import KernelDecode11.
Require Import KernelDecode12.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode18.
Require Import KernelDecode19.
Require Import KernelDecode20.
Require Import KernelDecode22.
Require Import KernelDecode23.
Require Import KernelDecode24.
Require Import KernelDecode25.
Require Import KernelDecode26.
Require Import KernelDecode27.
Require Import KernelDecode28.
Require Import KernelDecode29.
Require Import KernelDecode30.
Require Import KernelDecode31.
Require Import UserExecFacts.
Require Import TsoCtx.
Local Open Scope Z_scope.
Import Defs.


Section CodeConsoleintr.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId} `{XI : CurCtx}.

  (* ---- consoleintr @ KernelSyms.consoleintr, 364 bytes ---- *)

  Lemma cnti_000 : kernel_text -∗ instr (mword_of_int KernelSyms.consoleintr : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 61 : mword 6), sp, sp, ADDI)).
  Proof. mk_rvc KernelSyms.consoleintr (mword_of_int 0x7179 : mword 16)
    (mword_of_int KernelSyms.consoleintr : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 61 : mword 6), sp, sp, ADDI)) kd_7179 exec_execute_C_ADDI16SP. Qed.

  Lemma cnti_002 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 5 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x2) (mword_of_int 0xf406 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 5 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_f406 exec_execute_C_SDSP. Qed.

  Lemma cnti_004 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 4 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x4) (mword_of_int 0xf022 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 4 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_f022 exec_execute_C_SDSP. Qed.

  Lemma cnti_006 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x6) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x6) (mword_of_int 0xec26 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x6) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)) kd_ec26 exec_execute_C_SDSP. Qed.

  Lemma cnti_008 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x8) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 12 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x8) (mword_of_int 0x1800 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x8) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 12 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1800 exec_execute_C_ADDI4SPN. Qed.

  Lemma cnti_00a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xa) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xa) (mword_of_int 0x84aa : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xa) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)) kd_84aa exec_execute_C_MV. Qed.

  Lemma cnti_00c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xc) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0xc) (mword_of_int 0x00012517 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xc) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00012517. Qed.

  Lemma cnti_010 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x10) : mword 64) false (ITYPE (mword_of_int 4088 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x10) (mword_of_int 0xff850513 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x10) : mword 64) (ITYPE (mword_of_int 4088 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_ff850513. Qed.

  Lemma cnti_014 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x14) : mword 64) false (JAL (mword_of_int 2282 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x14) (mword_of_int 0x0eb000ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x14) : mword 64) (JAL (mword_of_int 2282 : mword 21, Regidx (mword_of_int 1))) kd_0eb000ef. Qed.

  Lemma cnti_018 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x18) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 21 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x18) (mword_of_int 0x47d5 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x18) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 21 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)) kd_47d5 exec_execute_C_LI. Qed.

  Lemma cnti_01a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x1a) : mword 64) false (BTYPE (mword_of_int 120 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0x1a) (mword_of_int 0x06f48c63 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x1a) : mword 64) (BTYPE (mword_of_int 120 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)) kd_06f48c63. Qed.

  Lemma cnti_01e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x1e) : mword 64) false (ITYPE (mword_of_int 127 : mword 12, zreg, Regidx (mword_of_int 15), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x1e) (mword_of_int 0x07f00793 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x1e) : mword 64) (ITYPE (mword_of_int 127 : mword 12, zreg, Regidx (mword_of_int 15), ADDI)) kd_07f00793. Qed.

  Lemma cnti_022 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x22) : mword 64) false (BTYPE (mword_of_int 206 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0x22) (mword_of_int 0x0cf48763 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x22) : mword 64) (BTYPE (mword_of_int 206 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)) kd_0cf48763. Qed.

  Lemma cnti_026 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x26) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 8 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x26) (mword_of_int 0x47a1 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x26) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 8 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)) kd_47a1 exec_execute_C_LI. Qed.

  Lemma cnti_028 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x28) : mword 64) false (BTYPE (mword_of_int 200 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0x28) (mword_of_int 0x0cf48463 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x28) : mword 64) (BTYPE (mword_of_int 200 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)) kd_0cf48463. Qed.

  Lemma cnti_02c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x2c) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 108 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 1)), BEQ)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x2c) (mword_of_int 0xcce1 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x2c) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 108 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 1)), BEQ)) kd_cce1 exec_execute_C_BEQZ. Qed.

  Lemma cnti_02e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x2e) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x2e) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x2e) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_032 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x32) : mword 64) false (ITYPE (mword_of_int 4054 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x32) (mword_of_int 0xfd670713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x32) : mword 64) (ITYPE (mword_of_int 4054 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)) kd_fd670713. Qed.

  Lemma cnti_036 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x36) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x36) (mword_of_int 0x0a072783 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x36) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)) kd_0a072783. Qed.

  Lemma cnti_03a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x3a) : mword 64) false (LOAD (mword_of_int 152 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x3a) (mword_of_int 0x09872703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x3a) : mword 64) (LOAD (mword_of_int 152 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)) kd_09872703. Qed.

  Lemma cnti_03e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x3e) : mword 64) true (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SUBW)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x3e) (mword_of_int 0x9f99 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x3e) : mword 64) (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SUBW)) kd_9f99 exec_execute_C_SUBW. Qed.

  Lemma cnti_040 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x40) : mword 64) false (ITYPE (mword_of_int 127 : mword 12, zreg, Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x40) (mword_of_int 0x07f00713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x40) : mword 64) (ITYPE (mword_of_int 127 : mword 12, zreg, Regidx (mword_of_int 14), ADDI)) kd_07f00713. Qed.

  Lemma cnti_044 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x44) : mword 64) false (BTYPE (mword_of_int 192 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BLTU)).
  Proof. mk_base (KernelSyms.consoleintr + 0x44) (mword_of_int 0x0cf76063 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x44) : mword 64) (BTYPE (mword_of_int 192 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BLTU)) kd_0cf76063. Qed.

  Lemma cnti_048 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x48) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 13 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x48) (mword_of_int 0x47b5 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x48) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 13 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)) kd_47b5 exec_execute_C_LI. Qed.

  Lemma cnti_04a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x4a) : mword 64) false (BTYPE (mword_of_int 228 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0x4a) (mword_of_int 0x0ef48263 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x4a) : mword 64) (BTYPE (mword_of_int 228 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ)) kd_0ef48263. Qed.

  Lemma cnti_04e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x4e) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x4e) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x4e) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma cnti_050 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x50) : mword 64) false (JAL (mword_of_int 2097022 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x50) (mword_of_int 0xf7fff0ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x50) : mword 64) (JAL (mword_of_int 2097022 : mword 21, Regidx (mword_of_int 1))) kd_f7fff0ef. Qed.

  Lemma cnti_054 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x54) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x54) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x54) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_058 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x58) : mword 64) false (ITYPE (mword_of_int 4016 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x58) (mword_of_int 0xfb070713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x58) : mword 64) (ITYPE (mword_of_int 4016 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)) kd_fb070713. Qed.

  Lemma cnti_05c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x5c) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 13), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x5c) (mword_of_int 0x0a072683 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x5c) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 13), false, 4)) kd_0a072683. Qed.

  Lemma cnti_060 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x60) : mword 64) false (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 15))).
  Proof. mk_base (KernelSyms.consoleintr + 0x60) (mword_of_int 0x0016879b : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x60) : mword 64) (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 15))) kd_0016879b. Qed.

  Lemma cnti_064 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x64) : mword 64) true (RTYPE (Regidx (mword_of_int 15), zreg, Regidx (mword_of_int 12), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x64) (mword_of_int 0x863e : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x64) : mword 64) (RTYPE (Regidx (mword_of_int 15), zreg, Regidx (mword_of_int 12), ADD)) kd_863e exec_execute_C_MV. Qed.

  Lemma cnti_066 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x66) : mword 64) false (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x66) (mword_of_int 0x0af72023 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x66) : mword 64) (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)) kd_0af72023. Qed.

  Lemma cnti_06a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x6a) : mword 64) false (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 13), ANDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x6a) (mword_of_int 0x07f6f693 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x6a) : mword 64) (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 13), ANDI)) kd_07f6f693. Qed.

  Lemma cnti_06e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x6e) : mword 64) true (RTYPE (Regidx (mword_of_int 13), Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x6e) (mword_of_int 0x9736 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x6e) : mword 64) (RTYPE (Regidx (mword_of_int 13), Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADD)) kd_9736 exec_execute_C_ADD. Qed.

  Lemma cnti_070 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x70) : mword 64) false (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), 1)).
  Proof. mk_base (KernelSyms.consoleintr + 0x70) (mword_of_int 0x00970c23 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x70) : mword 64) (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), 1)) kd_00970c23. Qed.

  Lemma cnti_074 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x74) : mword 64) false (ITYPE (mword_of_int 4086 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x74) (mword_of_int 0xff648713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x74) : mword 64) (ITYPE (mword_of_int 4086 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), ADDI)) kd_ff648713. Qed.

  Lemma cnti_078 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x78) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 111 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 6)), BEQ)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x78) (mword_of_int 0xcf79 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x78) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 111 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 6)), BEQ)) kd_cf79 exec_execute_C_BEQZ. Qed.

  Lemma cnti_07a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x7a) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 60 : mword 6), Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x7a) (mword_of_int 0x14f1 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x7a) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 60 : mword 6), Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)) kd_14f1 exec_execute_C_ADDI. Qed.

  Lemma cnti_07c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x7c) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 109 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 1)), BEQ)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x7c) (mword_of_int 0xcce9 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x7c) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 109 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 1)), BEQ)) kd_cce9 exec_execute_C_BEQZ. Qed.

  Lemma cnti_07e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x7e) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x7e) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x7e) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_082 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x82) : mword 64) false (LOAD (mword_of_int 30 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x82) (mword_of_int 0x01e72703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x82) : mword 64) (LOAD (mword_of_int 30 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)) kd_01e72703. Qed.

  Lemma cnti_086 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x86) : mword 64) true (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SUBW)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x86) (mword_of_int 0x9f99 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x86) : mword 64) (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SUBW)) kd_9f99 exec_execute_C_SUBW. Qed.

  Lemma cnti_088 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x88) : mword 64) false (ITYPE (mword_of_int 128 : mword 12, zreg, Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x88) (mword_of_int 0x08000713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x88) : mword 64) (ITYPE (mword_of_int 128 : mword 12, zreg, Regidx (mword_of_int 14), ADDI)) kd_08000713. Qed.

  Lemma cnti_08c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x8c) : mword 64) false (BTYPE (mword_of_int 120 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 15), BNE)).
  Proof. mk_base (KernelSyms.consoleintr + 0x8c) (mword_of_int 0x06e79c63 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x8c) : mword 64) (BTYPE (mword_of_int 120 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 15), BNE)) kd_06e79c63. Qed.

  Lemma cnti_090 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x90) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 99 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x90) (mword_of_int 0xa0d9 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x90) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 99 : mword 11) ('b"0")), zreg)) kd_a0d9 exec_execute_C_J. Qed.

  Lemma cnti_092 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x92) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x92) (mword_of_int 0xe84a : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x92) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)) kd_e84a exec_execute_C_SDSP. Qed.

  Lemma cnti_094 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x94) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 19), sp, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x94) (mword_of_int 0xe44e : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x94) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 19), sp, 8)) kd_e44e exec_execute_C_SDSP. Qed.

  Lemma cnti_096 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x96) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x96) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x96) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_09a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x9a) : mword 64) false (ITYPE (mword_of_int 3950 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x9a) (mword_of_int 0xf6e70713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x9a) : mword 64) (ITYPE (mword_of_int 3950 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)) kd_f6e70713. Qed.

  Lemma cnti_09e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x9e) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x9e) (mword_of_int 0x0a072783 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x9e) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)) kd_0a072783. Qed.

  Lemma cnti_0a2 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xa2) : mword 64) false (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xa2) (mword_of_int 0x09c72703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xa2) : mword 64) (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)) kd_09c72703. Qed.

  Lemma cnti_0a6 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xa6) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 9), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0xa6) (mword_of_int 0x00012497 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xa6) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 9), AUIPC)) kd_00012497. Qed.

  Lemma cnti_0aa : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xaa) : mword 64) false (ITYPE (mword_of_int 3934 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0xaa) (mword_of_int 0xf5e48493 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xaa) : mword 64) (ITYPE (mword_of_int 3934 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI)) kd_f5e48493. Qed.

  Lemma cnti_0ae : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xae) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 18), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xae) (mword_of_int 0x4929 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xae) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 18), ADDI)) kd_4929 exec_execute_C_LI. Qed.

  Lemma cnti_0b0 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xb0) : mword 64) false (ITYPE (mword_of_int 256 : mword 12, zreg, Regidx (mword_of_int 19), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0xb0) (mword_of_int 0x10000993 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xb0) : mword 64) (ITYPE (mword_of_int 256 : mword 12, zreg, Regidx (mword_of_int 19), ADDI)) kd_10000993. Qed.

  Lemma cnti_0b4 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xb4) : mword 64) false (BTYPE (mword_of_int 48 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0xb4) (mword_of_int 0x02f70863 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xb4) : mword 64) (BTYPE (mword_of_int 48 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BEQ)) kd_02f70863. Qed.

  Lemma cnti_0b8 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xb8) : mword 64) true (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xb8) (mword_of_int 0x37fd : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xb8) : mword 64) (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))) kd_37fd exec_execute_C_ADDIW. Qed.

  Lemma cnti_0ba : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xba) : mword 64) false (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), ANDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0xba) (mword_of_int 0x07f7f713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xba) : mword 64) (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), ANDI)) kd_07f7f713. Qed.

  Lemma cnti_0be : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xbe) : mword 64) true (RTYPE (Regidx (mword_of_int 9), Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xbe) (mword_of_int 0x9726 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xbe) : mword 64) (RTYPE (Regidx (mword_of_int 9), Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADD)) kd_9726 exec_execute_C_ADD. Qed.

  Lemma cnti_0c0 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xc0) : mword 64) false (LOAD (mword_of_int 24 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), true, 1)).
  Proof. mk_base (KernelSyms.consoleintr + 0xc0) (mword_of_int 0x01874703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xc0) : mword 64) (LOAD (mword_of_int 24 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), true, 1)) kd_01874703. Qed.

  Lemma cnti_0c4 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xc4) : mword 64) false (BTYPE (mword_of_int 38 : mword 13, Regidx (mword_of_int 18), Regidx (mword_of_int 14), BEQ)).
  Proof. mk_base (KernelSyms.consoleintr + 0xc4) (mword_of_int 0x03270363 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xc4) : mword 64) (BTYPE (mword_of_int 38 : mword 13, Regidx (mword_of_int 18), Regidx (mword_of_int 14), BEQ)) kd_03270363. Qed.

  Lemma cnti_0c8 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xc8) : mword 64) false (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xc8) (mword_of_int 0x0af4a023 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xc8) : mword 64) (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)) kd_0af4a023. Qed.

  Lemma cnti_0cc : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xcc) : mword 64) true (RTYPE (Regidx (mword_of_int 19), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xcc) (mword_of_int 0x854e : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xcc) : mword 64) (RTYPE (Regidx (mword_of_int 19), zreg, Regidx (mword_of_int 10), ADD)) kd_854e exec_execute_C_MV. Qed.

  Lemma cnti_0ce : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xce) : mword 64) false (JAL (mword_of_int 2096896 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0xce) (mword_of_int 0xf01ff0ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xce) : mword 64) (JAL (mword_of_int 2096896 : mword 21, Regidx (mword_of_int 1))) kd_f01ff0ef. Qed.

  Lemma cnti_0d2 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xd2) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xd2) (mword_of_int 0x0a04a783 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xd2) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_0a04a783. Qed.

  Lemma cnti_0d6 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xd6) : mword 64) false (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xd6) (mword_of_int 0x09c4a703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xd6) : mword 64) (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 4)) kd_09c4a703. Qed.

  Lemma cnti_0da : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xda) : mword 64) false (BTYPE (mword_of_int 8158 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BNE)).
  Proof. mk_base (KernelSyms.consoleintr + 0xda) (mword_of_int 0xfcf71fe3 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xda) : mword 64) (BTYPE (mword_of_int 8158 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BNE)) kd_fcf71fe3. Qed.

  Lemma cnti_0de : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xde) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xde) (mword_of_int 0x6942 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xde) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6942 exec_execute_C_LDSP. Qed.

  Lemma cnti_0e0 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xe0) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xe0) (mword_of_int 0x69a2 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xe0) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)) kd_69a2 exec_execute_C_LDSP. Qed.

  Lemma cnti_0e2 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xe2) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 17 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xe2) (mword_of_int 0xa00d : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xe2) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 17 : mword 11) ('b"0")), zreg)) kd_a00d exec_execute_C_J. Qed.

  Lemma cnti_0e4 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xe4) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xe4) (mword_of_int 0x6942 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xe4) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6942 exec_execute_C_LDSP. Qed.

  Lemma cnti_0e6 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xe6) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xe6) (mword_of_int 0x69a2 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xe6) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)) kd_69a2 exec_execute_C_LDSP. Qed.

  Lemma cnti_0e8 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xe8) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 14 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xe8) (mword_of_int 0xa831 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xe8) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 14 : mword 11) ('b"0")), zreg)) kd_a831 exec_execute_C_J. Qed.

  Lemma cnti_0ea : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xea) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xea) (mword_of_int 0x6942 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xea) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6942 exec_execute_C_LDSP. Qed.

  Lemma cnti_0ec : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xec) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xec) (mword_of_int 0x69a2 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xec) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 19), false, 8)) kd_69a2 exec_execute_C_LDSP. Qed.

  Lemma cnti_0ee : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xee) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 11 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0xee) (mword_of_int 0xa819 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0xee) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 11 : mword 11) ('b"0")), zreg)) kd_a819 exec_execute_C_J. Qed.

  Lemma cnti_0f0 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xf0) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0xf0) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xf0) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_0f4 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xf4) : mword 64) false (ITYPE (mword_of_int 3860 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0xf4) (mword_of_int 0xf1470713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xf4) : mword 64) (ITYPE (mword_of_int 3860 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)) kd_f1470713. Qed.

  Lemma cnti_0f8 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xf8) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xf8) (mword_of_int 0x0a072783 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xf8) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), false, 4)) kd_0a072783. Qed.

  Lemma cnti_0fc : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0xfc) : mword 64) false (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0xfc) (mword_of_int 0x09c72703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0xfc) : mword 64) (LOAD (mword_of_int 156 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), false, 4)) kd_09c72703. Qed.

  Lemma cnti_100 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x100) : mword 64) false (BTYPE (mword_of_int 26 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BNE)).
  Proof. mk_base (KernelSyms.consoleintr + 0x100) (mword_of_int 0x00f71d63 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x100) : mword 64) (BTYPE (mword_of_int 26 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BNE)) kd_00f71d63. Qed.

  Lemma cnti_104 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x104) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x104) (mword_of_int 0x00012517 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x104) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00012517. Qed.

  Lemma cnti_108 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x108) : mword 64) false (ITYPE (mword_of_int 3840 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x108) (mword_of_int 0xf0050513 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x108) : mword 64) (ITYPE (mword_of_int 3840 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_f0050513. Qed.

  Lemma cnti_10c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x10c) : mword 64) false (JAL (mword_of_int 2170 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x10c) (mword_of_int 0x07b000ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x10c) : mword 64) (JAL (mword_of_int 2170 : mword 21, Regidx (mword_of_int 1))) kd_07b000ef. Qed.

  Lemma cnti_110 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x110) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 5 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x110) (mword_of_int 0x70a2 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x110) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 5 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_70a2 exec_execute_C_LDSP. Qed.

  Lemma cnti_112 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x112) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 4 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x112) (mword_of_int 0x7402 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x112) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 4 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_7402 exec_execute_C_LDSP. Qed.

  Lemma cnti_114 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x114) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x114) (mword_of_int 0x64e2 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x114) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)) kd_64e2 exec_execute_C_LDSP. Qed.

  Lemma cnti_116 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x116) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 3 : mword 6), sp, sp, ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x116) (mword_of_int 0x6145 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x116) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 3 : mword 6), sp, sp, ADDI)) kd_6145 exec_execute_C_ADDI16SP. Qed.

  Lemma cnti_118 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x118) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x118) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x118) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

  Lemma cnti_11a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x11a) : mword 64) true (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x11a) (mword_of_int 0x37fd : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x11a) : mword 64) (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))) kd_37fd exec_execute_C_ADDIW. Qed.

  Lemma cnti_11c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x11c) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x11c) (mword_of_int 0x00012717 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x11c) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_00012717. Qed.

  Lemma cnti_120 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x120) : mword 64) false (STORE (mword_of_int 3976 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x120) (mword_of_int 0xf8f72423 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x120) : mword 64) (STORE (mword_of_int 3976 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)) kd_f8f72423. Qed.

  Lemma cnti_124 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x124) : mword 64) false (ITYPE (mword_of_int 256 : mword 12, zreg, Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x124) (mword_of_int 0x10000513 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x124) : mword 64) (ITYPE (mword_of_int 256 : mword 12, zreg, Regidx (mword_of_int 10), ADDI)) kd_10000513. Qed.

  Lemma cnti_128 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x128) : mword 64) false (JAL (mword_of_int 2096806 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x128) (mword_of_int 0xea7ff0ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x128) : mword 64) (JAL (mword_of_int 2096806 : mword 21, Regidx (mword_of_int 1))) kd_ea7ff0ef. Qed.

  Lemma cnti_12c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x12c) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 2028 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x12c) (mword_of_int 0xbfe1 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x12c) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 2028 : mword 11) ('b"0")), zreg)) kd_bfe1 exec_execute_C_J. Qed.

  Lemma cnti_12e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x12e) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 10), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x12e) (mword_of_int 0x4529 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x12e) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 10), ADDI)) kd_4529 exec_execute_C_LI. Qed.

  Lemma cnti_130 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x130) : mword 64) false (JAL (mword_of_int 2096798 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x130) (mword_of_int 0xe9fff0ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x130) : mword 64) (JAL (mword_of_int 2096798 : mword 21, Regidx (mword_of_int 1))) kd_e9fff0ef. Qed.

  Lemma cnti_134 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x134) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x134) (mword_of_int 0x00012797 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x134) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_00012797. Qed.

  Lemma cnti_138 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x138) : mword 64) false (ITYPE (mword_of_int 3792 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x138) (mword_of_int 0xed078793 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x138) : mword 64) (ITYPE (mword_of_int 3792 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_ed078793. Qed.

  Lemma cnti_13c : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x13c) : mword 64) false (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x13c) (mword_of_int 0x0a07a703 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x13c) : mword 64) (LOAD (mword_of_int 160 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 4)) kd_0a07a703. Qed.

  Lemma cnti_140 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x140) : mword 64) false (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 13))).
  Proof. mk_base (KernelSyms.consoleintr + 0x140) (mword_of_int 0x0017069b : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x140) : mword 64) (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 13))) kd_0017069b. Qed.

  Lemma cnti_144 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x144) : mword 64) true (RTYPE (Regidx (mword_of_int 13), zreg, Regidx (mword_of_int 12), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x144) (mword_of_int 0x8636 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x144) : mword 64) (RTYPE (Regidx (mword_of_int 13), zreg, Regidx (mword_of_int 12), ADD)) kd_8636 exec_execute_C_MV. Qed.

  Lemma cnti_146 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x146) : mword 64) false (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 15), 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x146) (mword_of_int 0x0ad7a023 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x146) : mword 64) (STORE (mword_of_int 160 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 15), 4)) kd_0ad7a023. Qed.

  Lemma cnti_14a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x14a) : mword 64) false (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ANDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x14a) (mword_of_int 0x07f77713 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x14a) : mword 64) (ITYPE (mword_of_int 127 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ANDI)) kd_07f77713. Qed.

  Lemma cnti_14e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x14e) : mword 64) true (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADD)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x14e) (mword_of_int 0x97ba : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x14e) : mword 64) (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADD)) kd_97ba exec_execute_C_ADD. Qed.

  Lemma cnti_150 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x150) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 14), ADDI)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x150) (mword_of_int 0x4729 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x150) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 10 : mword 6), zreg, Regidx (mword_of_int 14), ADDI)) kd_4729 exec_execute_C_LI. Qed.

  Lemma cnti_152 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x152) : mword 64) false (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 1)).
  Proof. mk_base (KernelSyms.consoleintr + 0x152) (mword_of_int 0x00e78c23 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x152) : mword 64) (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 1)) kd_00e78c23. Qed.

  Lemma cnti_156 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x156) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x156) (mword_of_int 0x00012797 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x156) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_00012797. Qed.

  Lemma cnti_15a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x15a) : mword 64) false (STORE (mword_of_int 3914 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 15), 4)).
  Proof. mk_base (KernelSyms.consoleintr + 0x15a) (mword_of_int 0xf4c7a523 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x15a) : mword 64) (STORE (mword_of_int 3914 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 15), 4)) kd_f4c7a523. Qed.

  Lemma cnti_15e : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x15e) : mword 64) false (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof. mk_base (KernelSyms.consoleintr + 0x15e) (mword_of_int 0x00012517 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x15e) : mword 64) (UTYPE (mword_of_int 18 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00012517. Qed.

  Lemma cnti_162 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x162) : mword 64) false (ITYPE (mword_of_int 3902 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.consoleintr + 0x162) (mword_of_int 0xf3e50513 : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x162) : mword 64) (ITYPE (mword_of_int 3902 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_f3e50513. Qed.

  Lemma cnti_166 : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x166) : mword 64) false (JAL (mword_of_int 6974 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.consoleintr + 0x166) (mword_of_int 0x33f010ef : mword 32)
    (mword_of_int (KernelSyms.consoleintr + 0x166) : mword 64) (JAL (mword_of_int 6974 : mword 21, Regidx (mword_of_int 1))) kd_33f010ef. Qed.

  Lemma cnti_16a : kernel_text -∗ instr (mword_of_int (KernelSyms.consoleintr + 0x16a) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 1997 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.consoleintr + 0x16a) (mword_of_int 0xbf69 : mword 16)
    (mword_of_int (KernelSyms.consoleintr + 0x16a) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 1997 : mword 11) ('b"0")), zreg)) kd_bf69 exec_execute_C_J. Qed.

End CodeConsoleintr.
