(* CodePanic.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's panic: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [pni_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode11.
Require Import KernelDecode22.
Require Import KernelDecode24.
Local Open Scope Z_scope.
Import Defs.


Section CodePanic.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- panic @ KernelSyms.panic, 10 bytes ---- *)

  Lemma pni_00 : kernel_text -∗ instr (mword_of_int KernelSyms.panic : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof. mk_rvc KernelSyms.panic (mword_of_int 0x1141 : mword 16)
    (mword_of_int KernelSyms.panic : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1141 exec_execute_C_ADDI. Qed.

  Lemma pni_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.panic + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof. mk_rvc (KernelSyms.panic + 0x2) (mword_of_int 0xe406 : mword 16)
    (mword_of_int (KernelSyms.panic + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_e406 exec_execute_C_SDSP. Qed.

  Lemma pni_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.panic + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof. mk_rvc (KernelSyms.panic + 0x4) (mword_of_int 0xe022 : mword 16)
    (mword_of_int (KernelSyms.panic + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e022 exec_execute_C_SDSP. Qed.

  Lemma pni_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.panic + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof. mk_rvc (KernelSyms.panic + 0x6) (mword_of_int 0x0800 : mword 16)
    (mword_of_int (KernelSyms.panic + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_0800 exec_execute_C_ADDI4SPN. Qed.

  Lemma pni_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.panic + 0x8) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 0 : mword 11) ('b"0")), zreg)).
  Proof. mk_rvc (KernelSyms.panic + 0x8) (mword_of_int 0xa001 : mword 16)
    (mword_of_int (KernelSyms.panic + 0x8) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 0 : mword 11) ('b"0")), zreg)) kd_a001 exec_execute_C_J. Qed.

End CodePanic.
