(* CodeAllocpid.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's allocpid: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [apdi_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From Stdlib Require Import ZArith.
From stdpp Require Import bitvector.definitions.
From iris.proofmode Require Import proofmode.
From iris.program_logic Require Import lifting.
Require Import SailStdpp.ConcurrencyInterface SailStdpp.ConcurrencyInterfaceBuiltins SailStdpp.ConcurrencyInterfaceTypes SailStdpp.Operators_mwords.
Require Import Riscv.rv64d_types Riscv.rv64d Riscv.riscv_extras.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto RiscvExec RiscvFetchExec.
Require Import InstrBytes WpDecodeBridge.
Require Import KernelText.
Require Import WpMmodeLeafBase.
Require Import WpRvcBridge.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode.
Require Import ExecCommon.
Local Open Scope Z_scope.
Import Defs.


Section CodeAllocpid.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- allocpid @ KernelSyms.allocpid, 62 bytes ---- *)

  Lemma apdi_00 : kernel_text -∗ instr (mword_of_int KernelSyms.allocpid : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof. mk_rvc KernelSyms.allocpid (mword_of_int 0x1101 : mword 16)
    (mword_of_int KernelSyms.allocpid : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1101 exec_execute_C_ADDI. Qed.

  Lemma apdi_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x2) (mword_of_int 0xec06 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_ec06 exec_execute_C_SDSP. Qed.

  Lemma apdi_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x4) (mword_of_int 0xe822 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e822 exec_execute_C_SDSP. Qed.

  Lemma apdi_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x6) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x6) (mword_of_int 0xe426 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x6) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)) kd_e426 exec_execute_C_SDSP. Qed.

  Lemma apdi_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x8) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x8) (mword_of_int 0x1000 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x8) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1000 exec_execute_C_ADDI4SPN. Qed.

  Lemma apdi_0a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0xa) : mword 64) false (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof. mk_base (KernelSyms.allocpid + 0xa) (mword_of_int 0x00011517 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0xa) : mword 64) (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00011517. Qed.

  Lemma apdi_0e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0xe) : mword 64) false (ITYPE (mword_of_int 2414 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.allocpid + 0xe) (mword_of_int 0x96e50513 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0xe) : mword 64) (ITYPE (mword_of_int 2414 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_96e50513. Qed.

  Lemma apdi_12 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x12) : mword 64) false (JAL (mword_of_int 2093606 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocpid + 0x12) (mword_of_int 0xa26ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x12) : mword 64) (JAL (mword_of_int 2093606 : mword 21, Regidx (mword_of_int 1))) kd_a26ff0ef. Qed.

  Lemma apdi_16 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x16) : mword 64) false (UTYPE (mword_of_int 9 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof. mk_base (KernelSyms.allocpid + 0x16) (mword_of_int 0x00009797 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x16) : mword 64) (UTYPE (mword_of_int 9 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_00009797. Qed.

  Lemma apdi_1a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x1a) : mword 64) false (ITYPE (mword_of_int 2062 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof. mk_base (KernelSyms.allocpid + 0x1a) (mword_of_int 0x80e78793 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x1a) : mword 64) (ITYPE (mword_of_int 2062 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_80e78793. Qed.

  Lemma apdi_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x1e) : mword 64) true (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), false, 4)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x1e) (mword_of_int 0x4384 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x1e) : mword 64) (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), false, 4)) kd_4384 ke_4384. Qed.

  Lemma apdi_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x20) : mword 64) false (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14))).
  Proof. mk_base (KernelSyms.allocpid + 0x20) (mword_of_int 0x0014871b : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x20) : mword 64) (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14))) kd_0014871b. Qed.

  Lemma apdi_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x24) : mword 64) true (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 4)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x24) (mword_of_int 0xc398 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x24) : mword 64) (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 4)) kd_c398 ke_c398. Qed.

  Lemma apdi_26 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x26) : mword 64) false (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof. mk_base (KernelSyms.allocpid + 0x26) (mword_of_int 0x00011517 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x26) : mword 64) (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00011517. Qed.

  Lemma apdi_2a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x2a) : mword 64) false (ITYPE (mword_of_int 2386 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof. mk_base (KernelSyms.allocpid + 0x2a) (mword_of_int 0x95250513 : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x2a) : mword 64) (ITYPE (mword_of_int 2386 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_95250513. Qed.

  Lemma apdi_2e : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x2e) : mword 64) false (JAL (mword_of_int 2093714 : mword 21, Regidx (mword_of_int 1))).
  Proof. mk_base (KernelSyms.allocpid + 0x2e) (mword_of_int 0xa92ff0ef : mword 32)
    (mword_of_int (KernelSyms.allocpid + 0x2e) : mword 64) (JAL (mword_of_int 2093714 : mword 21, Regidx (mword_of_int 1))) kd_a92ff0ef. Qed.

  Lemma apdi_32 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x32) : mword 64) true (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x32) (mword_of_int 0x8526 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x32) : mword 64) (RTYPE (Regidx (mword_of_int 9), zreg, Regidx (mword_of_int 10), ADD)) kd_8526 exec_execute_C_MV. Qed.

  Lemma apdi_34 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x34) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x34) (mword_of_int 0x60e2 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x34) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60e2 exec_execute_C_LDSP. Qed.

  Lemma apdi_36 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x36) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x36) (mword_of_int 0x6442 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x36) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6442 exec_execute_C_LDSP. Qed.

  Lemma apdi_38 : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x38) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x38) (mword_of_int 0x64a2 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x38) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)) kd_64a2 exec_execute_C_LDSP. Qed.

  Lemma apdi_3a : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x3a) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x3a) (mword_of_int 0x6105 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x3a) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)) kd_6105 exec_execute_C_ADDI16SP. Qed.

  Lemma apdi_3c : kernel_text -∗ instr (mword_of_int (KernelSyms.allocpid + 0x3c) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof. mk_rvc (KernelSyms.allocpid + 0x3c) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.allocpid + 0x3c) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeAllocpid.
