(* ====================================================================== *)
(*  FsBootWall.v -- CLOSED BY durable-disk LANE G6.                        *)
(*                                                                        *)
(*  THE RECORD OF A WALL THAT NO LONGER EXISTS: why the era's file-system  *)
(*  instance could not be minted from the durable snapshot for as long as  *)
(*  the OLD LINK LEDGER was carried, and what removing the ledger did to   *)
(*  the obstruction.  Kept, as [FsDurRefute.v] and [FsDurDefer.v] are      *)
(*  kept, so that the next lane does not re-derive the mint that could     *)
(*  not close -- and so that the reason it CAN close now is written down   *)
(*  where the reason it could not used to be.                              *)
(* ---------------------------------------------------------------------- *)
(*                                                                        *)
(*  THE TASK.  durable-fs-plan.md §5 wants the era's instance minted at    *)
(*  boot from the durable snapshot -- [FsDurSnap.fs_state_of_ledger_era]   *)
(*  off [FsDurSnap.snap_ok S D] -- in place of the boot-time decoding of   *)
(*  fs.img, so that [FsCfgBoot.fs_boot_image_wf] stops being load-bearing  *)
(*  at every era.  Measured, the FILE-SYSTEM PREDICATE's own content --    *)
(*  the node map, the records, the data and indirect blocks, the bitmap    *)
(*  and the free pool, the abstract map, and the [FsStateLink] link        *)
(*  family -- all comes off [snap_ok], once lane E-boot's two new clauses  *)
(*  ([FsStateInode.inl_bare_free] and [FsDurSnap.sk_regdom]) are in and    *)
(*  the root's keep-alive slack is added beside [sk_links].                *)
(*                                                                        *)
(*  THE WALL, AS IT STOOD.  What did NOT come off [snap_ok] at all was the *)
(*  old link ledger: [DirLinks.dir_links] and the inode region's flavoured *)
(*  columns.  The boot's ONLY constructor for a directory's [dir_links]    *)
(*  was the ALL-PLAIN stock [DirLinks.dir_links_of_plain], and the         *)
(*  all-plain stock is a fact about the MKFS IMAGE -- it forces every live *)
(*  directory to have [nlink <= 1] (the count clause [DirView.dlc_bound]   *)
(*  at the all-false flavour map counts nothing) and, if the directory has *)
(*  a dotdot record, to BE the root ([DirLinks.dir_par_tie]'s root         *)
(*  exclusion).  Both are false at any era in which mkdir has ever run,    *)
(*  because create's mkdir arm does [dp->nlink++] ([ProofCreate], +0x134)  *)
(*  and pays for it with a d-FLAVOURED ticket.  The region's side of the   *)
(*  same fact: [IcacheBoot.ireg_alloc] handed the region its authorities   *)
(*  with the d columns and the parent register at ZERO, and its premise    *)
(*  [image_dir_wl0] ([InodeRegion.ireg_dir_wl0]) said no PLAIN ticket      *)
(*  names a directory -- which the plain stock violates at the first       *)
(*  subdirectory.                                                         *)
(*                                                                        *)
(*  Both halves were machine-checked here, as [boot_plain_stock_refuted]   *)
(*  ([2 <= nlink -> ~ dlc_bound (fun _ => false) dn data], an IFF away     *)
(*  from [nlink <= 1], so no proof effort could weaken it) and             *)
(*  [boot_dir_wl0_refuted].  Both statements are DELETED with the objects  *)
(*  they quantified over; the arithmetic was never the point.             *)
(*                                                                        *)
(*  HOW IT CLOSED, and it closed by DEMOLITION rather than by repair.      *)
(*  The three routes this file listed --                                   *)
(*    (a) a flavour-map-aware stock in [DirLinks] (needs the TARGET's      *)
(*        type, cross-inode information the snapshot's per-object clauses  *)
(*        deliberately do not carry, plus the exact accounting             *)
(*        [nlink <= 1 + #subdirectories]);                                 *)
(*    (b) the parent registers ([DirLinks.dir_par_tie]) minted at boot off *)
(*        each directory's record 1;                                       *)
(*    (c) [ireg_alloc]'s ledger premise generalised to nonzero [wdu]/[wdt] *)
(*        and a non-None parent register                                   *)
(*  -- were all about objects lane G6 removed.  Link counts and types are  *)
(*  ONE resource algebra now (design/fs-state.md §6½): an                  *)
(*  [auth (gmultiset ity)] per inum whose FRAGMENTS are the counted        *)
(*  dirents, so a dirent's own unit reveals its target's type and there is *)
(*  no second ledger to stock.  [IcacheEscrow.dlinks] is                    *)
(*  [FsStateInode.ent_toks_x] alone; [IcacheRef]'s element is [c]/[r] plus *)
(*  [f]/[rc]; the [fl] index is gone from [SpecIupdate]'s two link bodies. *)
(*  What the boot builds instead is what [FsCfgBoot.ent_toks_of_region]    *)
(*  already builds and [FsDurImg] section 9 already routes: ONE value      *)
(*  function [fv : Z -> ity], a key's whole pile [link_reps (count) (fv z)] *)
(*  by [FsStateLink.link_reps_add], and per-directory exactness            *)
(*  ([FsStateInode.node_exact]) at the marker set -- all per-object, and   *)
(*  all admissible under plan §4's rule.  The cross-inode reading that     *)
(*  remains ([FsDurSnap.sk_links]'s "each dirent's fragment from its       *)
(*  target's type") is the ONE the ruling sanctions and lane H removes.    *)
(*                                                                        *)
(*  THREE FURTHER CLAUSES THE POOL NEEDS AND [snap_ok] DOES NOT CARRY --   *)
(*  unchanged by G6, and still the next lane's sweep.  All per-object, all *)
(*  already re-proved at every iunlock by the escrow arms, none of them a  *)
(*  cross-inode content clause.  [IcacheBoot.ipool_alloc]'s per-inum       *)
(*  bundle demands [DirView.dir_ok] (every entry's inum is inside the      *)
(*  region), [DirView.dir_dots_ix] (a live directory's records 0 and 1 ARE *)
(*  its dot and dotdot records -- POSITIONALLY, which                      *)
(*  [FsStateInode.inl_dir_dot] does not say: that clause is about the      *)
(*  entry VIEW [FsStateInode.dir_entries], a name-to-inum gmap blind to    *)
(*  which record carries the name) and [DirView.dir_orphan_clean].         *)
(*                                                                        *)
(*  The retired ledger's own sources are kept off [_CoqProject] at         *)
(*  [iris/DirLinks.v] and [iris/IregDirBit.v]; read their headers for the  *)
(*  mechanism this file refuted.                                          *)
(* ====================================================================== *)
