(* KernelDecode30.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for shard 30 of 32 of the kernel image's instruction words: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [kd_<word> / ke_<word>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvExec RiscvFetchExec.
Require Import WpMmodeLeafBase.
Require Import WpDecodeBridge.
Require Import WpRvcBridge.
Local Open Scope Z_scope.
Import Defs.

Lemma kd_048a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x048a : mword 16)) s
  = Some (C_SLLI (mword_of_int 2, Regidx (mword_of_int 9)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_17fe s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x17fe : mword 16)) s
  = Some (C_SLLI (mword_of_int 63, Regidx (mword_of_int 15)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_411c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x411c : mword 16)) s
  = Some (C_LW (mword_of_int 0, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_411c s :
  exec (execute (C_LW (mword_of_int 0, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 4)), s).
Proof. apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_461d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x461d : mword 16)) s
  = Some (C_LI (mword_of_int 7, Regidx (mword_of_int 12)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4689 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4689 : mword 16)) s
  = Some (C_LI (mword_of_int 2, Regidx (mword_of_int 13)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4745 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4745 : mword 16)) s
  = Some (C_LI (mword_of_int 17, Regidx (mword_of_int 14)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_479d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x479d : mword 16)) s
  = Some (C_LI (mword_of_int 7, Regidx (mword_of_int 15)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_47c1 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x47c1 : mword 16)) s
  = Some (C_LI (mword_of_int 16, Regidx (mword_of_int 15)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4a0d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4a0d : mword 16)) s
  = Some (C_LI (mword_of_int 3, Regidx (mword_of_int 20)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4c11 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4c11 : mword 16)) s
  = Some (C_LI (mword_of_int 4, Regidx (mword_of_int 24)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_691e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x691e : mword 16)) s
  = Some (C_LDSP (mword_of_int 56, Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_69e2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x69e2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 3, Regidx (mword_of_int 19)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_6be2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6be2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 3, Regidx (mword_of_int 23)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_70e6 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x70e6 : mword 16)) s
  = Some (C_LDSP (mword_of_int 15, Regidx (mword_of_int 1)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7406 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7406 : mword 16)) s
  = Some (C_LDSP (mword_of_int 12, Regidx (mword_of_int 8)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7906 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7906 : mword 16)) s
  = Some (C_LDSP (mword_of_int 12, Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7a02 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7a02 : mword 16)) s
  = Some (C_LDSP (mword_of_int 4, Regidx (mword_of_int 20)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7d02 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7d02 : mword 16)) s
  = Some (C_LDSP (mword_of_int 4, Regidx (mword_of_int 26)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_83a9 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x83a9 : mword 16)) s
  = Some (C_SRLI (mword_of_int 10, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_85e2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x85e2 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 11), Regidx (mword_of_int 24)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_00008797 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00008797 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 8 : mword 20, Regidx (mword_of_int 15), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_8b2a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8b2a : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 22), Regidx (mword_of_int 10)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_962a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x962a : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 12), Regidx (mword_of_int 10)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a015 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa015 : mword 16)) s
  = Some (C_J (mword_of_int 18), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_bf19 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbf19 : mword 16)) s
  = Some (C_J (mword_of_int 1931), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_c0dc s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc0dc : mword 16)) s
  = Some (C_SW (mword_of_int 1, Cregidx (mword_of_int 1), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_c0dc s :
  exec (execute (C_SW (mword_of_int 1, Cregidx (mword_of_int 1), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 4 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_c19c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc19c : mword 16)) s
  = Some (C_SW (mword_of_int 0, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_c19c s :
  exec (execute (C_SW (mword_of_int 0, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 11), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_c511 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc511 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 6, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_c549 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc549 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 69, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_c935 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc935 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 58, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_cb14 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xcb14 : mword 16)) s
  = Some (C_SW (mword_of_int 4, Cregidx (mword_of_int 6), Cregidx (mword_of_int 5)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_cb14 s :
  exec (execute (C_SW (mword_of_int 4, Cregidx (mword_of_int 6), Cregidx (mword_of_int 5)))) s
  = Some (ExecuteAs (STORE (mword_of_int 16 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 14), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_cb91 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xcb91 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 10, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_ce11 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xce11 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 14, Cregidx (mword_of_int 4)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_d75c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xd75c : mword 16)) s
  = Some (C_SW (mword_of_int 11, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_d75c s :
  exec (execute (C_SW (mword_of_int 11, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 44 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_dbc1 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xdbc1 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 200, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_dd65 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xdd65 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 252, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_df98 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xdf98 : mword 16)) s
  = Some (C_SW (mword_of_int 14, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_df98 s :
  exec (execute (C_SW (mword_of_int 14, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)))) s
  = Some (ExecuteAs (STORE (mword_of_int 56 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_e506 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe506 : mword 16)) s
  = Some (C_SDSP (mword_of_int 17, Regidx (mword_of_int 1)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_e526 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe526 : mword 16)) s
  = Some (C_SDSP (mword_of_int 17, Regidx (mword_of_int 9)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_e86a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe86a : mword 16)) s
  = Some (C_SDSP (mword_of_int 2, Regidx (mword_of_int 26)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_ef1c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xef1c : mword 16)) s
  = Some (C_SD (mword_of_int 3, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_ef1c s :
  exec (execute (C_SD (mword_of_int 3, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 8)), s).
Proof. apply exec_execute_C_SD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_ef95 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xef95 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 30, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_f0fd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf0fd : mword 16)) s
  = Some (C_BNEZ (mword_of_int 243, Cregidx (mword_of_int 1)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_f36d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf36d : mword 16)) s
  = Some (C_BNEZ (mword_of_int 241, Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_fb65 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xfb65 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 248, Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_0001e517 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0001e517 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 10), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0009079b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0009079b : mword 32) : M instruction) s
  = Some (ADDIW (mword_of_int 0 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 15)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00174683 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00174683 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 1 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 13), true, 1), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00878633 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00878633 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 8), Regidx (mword_of_int 15), Regidx (mword_of_int 12), ADD), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00c4d613 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00c4d613 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 12 : mword 6, Regidx (mword_of_int 9), Regidx (mword_of_int 12), SRLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00d780a3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00d780a3 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 1 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 15), 1), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00e904b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e904b3 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 18), Regidx (mword_of_int 9), ADD), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00e92023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e92023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 18), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00f48ea3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f48ea3 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 29 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 1), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00f59523 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f59523 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 10 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 11), 2), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00f9ac23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f9ac23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 19), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0164a023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0164a023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 22), Regidx (mword_of_int 9), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_01acdc93 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x01acdc93 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 26 : mword 6, Regidx (mword_of_int 25), Regidx (mword_of_int 25), SRLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_02092023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02092023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 32 : mword 12, zreg, Regidx (mword_of_int 18), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_02092783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02092783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 32 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 15), false, 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_020ddd93 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x020ddd93 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 27), Regidx (mword_of_int 27), SRLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_02c05363 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02c05363 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 38 : mword 13, Regidx (mword_of_int 12), zreg, BGE), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04054363 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04054363 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 70 : mword 13, zreg, Regidx (mword_of_int 10), BLT), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04078793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04078793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 64 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_040a8263 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x040a8263 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 68 : mword 13, zreg, Regidx (mword_of_int 21), BEQ), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_048ab783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x048ab783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 72 : mword 12, Regidx (mword_of_int 21), Regidx (mword_of_int 15), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04caa783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04caa783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 76 : mword 12, Regidx (mword_of_int 21), Regidx (mword_of_int 15), false, 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04f70d63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04f70d63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 90 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BEQ), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_08c58593 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x08c58593 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 140 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_08f70463 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x08f70463 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 136 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BEQ), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0ad76f63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0ad76f63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 190 : mword 13, Regidx (mword_of_int 13), Regidx (mword_of_int 14), BLTU), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0c000637 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0c000637 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 49152 : mword 20, Regidx (mword_of_int 12), LUI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0ff4f513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0ff4f513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 255 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ANDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_104020ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x104020ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 8452 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_1fa000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x1fa000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 506 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_30379073 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x30379073 : mword 32) : M instruction) s
  = Some (CSRReg (mword_of_int 771 : mword 12, Regidx (mword_of_int 15), zreg, CSRRW), s).
Proof. decode_bridge_ms_bv. Qed.

Lemma kd_49850513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x49850513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1176 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_62250513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x62250513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1570 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_6ae78793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x6ae78793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1710 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_80eff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x80eff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2093070 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_843fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x843fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2086978 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_86dfd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x86dfd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2087020 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_8d4a0a13 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x8d4a0a13 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 2260 : mword 12, Regidx (mword_of_int 20), Regidx (mword_of_int 20), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_91fff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x91fff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095390 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_a0efe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa0efe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2089486 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_a47fb0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa47fb0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2079302 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_a68fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa68fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2081384 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_a7cfe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa7cfe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2089596 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_b07fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb07fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091782 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_b29ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb29ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095912 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_b64ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb64ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2093924 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_c41ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc41ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096192 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_c93fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc93fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2092178 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_caeff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xcaeff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2094254 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_d39ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd39ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096440 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_d7cff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd7cff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2094460 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_e59fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe59fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2084440 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_e61ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe61ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096736 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ecfff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xecfff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096846 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ee5ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xee5ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096868 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f3dff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf3dff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096956 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f65ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf65ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096996 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f70ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf70ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2094960 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fa842603 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfa842603 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 4008 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 12), false, 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fce57ae3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfce57ae3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8148 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 10), BGEU), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fe043503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfe043503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 4064 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fe04d7e3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfe04d7e3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8174 : mword 13, zreg, Regidx (mword_of_int 9), BGE), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ff478793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xff478793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 4084 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof. decode_bridge_ms. Qed.

