(* KernelDecode28.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for shard 28 of 32 of the kernel image's instruction words: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [kd_<word> / ke_<word>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvExec RiscvFetchExec.
Require Import WpMmodeLeafBase.
Require Import WpDecodeBridge.
Require Import WpRvcBridge.
Local Open Scope Z_scope.
Import Defs.

Lemma kd_0721 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x0721 : mword 16)) s
  = Some (C_ADDI (mword_of_int 8, Regidx (mword_of_int 14)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_0905 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x0905 : mword 16)) s
  = Some (C_ADDI (mword_of_int 1, Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_2a05 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x2a05 : mword 16)) s
  = Some (C_ADDIW (mword_of_int 1, Regidx (mword_of_int 20)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4301 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4301 : mword 16)) s
  = Some (C_LI (mword_of_int 0, Regidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4639 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4639 : mword 16)) s
  = Some (C_LI (mword_of_int 14, Regidx (mword_of_int 12)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_46c1 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x46c1 : mword 16)) s
  = Some (C_LI (mword_of_int 16, Regidx (mword_of_int 13)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_4901 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4901 : mword 16)) s
  = Some (C_LI (mword_of_int 0, Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_00004a17 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00004a17 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 20), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_651c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x651c : mword 16)) s
  = Some (C_LD (mword_of_int 1, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_651c s :
  exec (execute (C_LD (mword_of_int 1, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 8)), s).
Proof. apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_6685 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6685 : mword 16)) s
  = Some (C_LUI (mword_of_int 1, Regidx (mword_of_int 13)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_690a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x690a : mword 16)) s
  = Some (C_LDSP (mword_of_int 16, Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_69e6 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x69e6 : mword 16)) s
  = Some (C_LDSP (mword_of_int 11, Regidx (mword_of_int 19)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_740e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x740e : mword 16)) s
  = Some (C_LDSP (mword_of_int 28, Regidx (mword_of_int 8)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_744a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x744a : mword 16)) s
  = Some (C_LDSP (mword_of_int 22, Regidx (mword_of_int 8)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7779 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7779 : mword 16)) s
  = Some (C_LUI (mword_of_int 62, Regidx (mword_of_int 14)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7a5a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7a5a : mword 16)) s
  = Some (C_LDSP (mword_of_int 54, Regidx (mword_of_int 20)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7a5e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7a5e : mword 16)) s
  = Some (C_LDSP (mword_of_int 62, Regidx (mword_of_int 20)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7aa2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7aa2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 5, Regidx (mword_of_int 21)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_7bb8 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7bb8 : mword 16)) s
  = Some (C_LD (mword_of_int 14, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_7bb8 s :
  exec (execute (C_LD (mword_of_int 14, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 112 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)), s).
Proof. apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_8662 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8662 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 12), Regidx (mword_of_int 24)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_8666 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8666 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 12), Regidx (mword_of_int 25)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_89da s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x89da : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 19), Regidx (mword_of_int 22)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_8a26 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8a26 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 20), Regidx (mword_of_int 9)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_8b36 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8b36 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 22), Regidx (mword_of_int 13)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_8b8d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8b8d : mword 16)) s
  = Some (C_ANDI (mword_of_int 3, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_8b8d s :
  exec (execute (C_ANDI (mword_of_int 3, Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (ITYPE (sign_extend' 12 (mword_of_int 3 : mword 6), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), ANDI)), s).
Proof. apply exec_execute_C_ANDI_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_8d5d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8d5d : mword 16)) s
  = Some (C_OR (Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_8d5d s :
  exec (execute (C_OR (Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (RTYPE (creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 2)), creg2reg_idx (Cregidx (mword_of_int 2)), OR)), s).
Proof. apply exec_execute_C_OR_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_95e2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x95e2 : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 11), Regidx (mword_of_int 24)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_97ae s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x97ae : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 15), Regidx (mword_of_int 11)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_9a4a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x9a4a : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 20), Regidx (mword_of_int 18)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a07d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa07d : mword 16)) s
  = Some (C_J (mword_of_int 87), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a831 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa831 : mword 16)) s
  = Some (C_J (mword_of_int 14), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a83d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa83d : mword 16)) s
  = Some (C_J (mword_of_int 31), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a891 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa891 : mword 16)) s
  = Some (C_J (mword_of_int 42), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_a8b9 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa8b9 : mword 16)) s
  = Some (C_J (mword_of_int 47), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_b3b1 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb3b1 : mword 16)) s
  = Some (C_J (mword_of_int 1702), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_b7a5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb7a5 : mword 16)) s
  = Some (C_J (mword_of_int 1972), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_c93d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc93d : mword 16)) s
  = Some (C_BEQZ (mword_of_int 59, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_cd15 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xcd15 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 30, Cregidx (mword_of_int 2)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_db1c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xdb1c : mword 16)) s
  = Some (C_SW (mword_of_int 12, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_db1c s :
  exec (execute (C_SW (mword_of_int 12, Cregidx (mword_of_int 6), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 48 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 4)), s).
Proof. apply exec_execute_C_SW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_e38d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe38d : mword 16)) s
  = Some (C_BNEZ (mword_of_int 17, Cregidx (mword_of_int 7)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_ec56 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xec56 : mword 16)) s
  = Some (C_SDSP (mword_of_int 3, Regidx (mword_of_int 21)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_f398 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf398 : mword 16)) s
  = Some (C_SD (mword_of_int 4, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma ke_f398 s :
  exec (execute (C_SD (mword_of_int 4, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)))) s
  = Some (ExecuteAs (STORE (mword_of_int 32 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 8)), s).
Proof. apply exec_execute_C_SD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_f586 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf586 : mword 16)) s
  = Some (C_SDSP (mword_of_int 29, Regidx (mword_of_int 1)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_ff65 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xff65 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 252, Cregidx (mword_of_int 6)), s).
Proof. intro H. rvc_oneshot s H. Qed.

Lemma kd_00010b17 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00010b17 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 16 : mword 20, Regidx (mword_of_int 22), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00016517 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00016517 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 22 : mword 20, Regidx (mword_of_int 10), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0001e797 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0001e797 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 15), AUIPC), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0004ac23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0004ac23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 24 : mword 12, zreg, Regidx (mword_of_int 9), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00053823 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00053823 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 16 : mword 12, zreg, Regidx (mword_of_int 10), 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0009b783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0009b783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 19), Regidx (mword_of_int 15), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_000a57b7 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x000a57b7 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 165 : mword 20, Regidx (mword_of_int 15), LUI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0027d783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0027d783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 2 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), true, 2), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00568713 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00568713 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 5 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 14), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_009b07b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x009b07b3 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 9), Regidx (mword_of_int 22), Regidx (mword_of_int 15), ADD), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00c71623 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00c71623 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 12 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 14), 2), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00d5151b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00d5151b : mword 32) : M instruction) s
  = Some (SHIFTIWOP (mword_of_int 13 : mword 5, Regidx (mword_of_int 10), Regidx (mword_of_int 10), SLLIW), s).
Proof. decode_bridge_ms_bv. Qed.

Lemma kd_00d71623 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00d71623 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 12 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 14), 2), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_00fc7c33 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00fc7c33 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 15), Regidx (mword_of_int 24), Regidx (mword_of_int 24), AND), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_015904b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x015904b3 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 21), Regidx (mword_of_int 18), Regidx (mword_of_int 9), ADD), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0204d783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0204d783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 32 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), true, 2), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_02079713 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02079713 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 15), Regidx (mword_of_int 14), SLLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0230000f s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0230000f : mword 32) : M instruction) s
  = Some (FENCE (mword_of_int 0 : mword 4, mword_of_int 2 : mword 4, mword_of_int 3 : mword 4, zreg, zreg), s).
Proof. decode_bridge_ms_bv. Qed.

Lemma kd_02800513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02800513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 40 : mword 12, zreg, Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0285b983 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0285b983 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 40 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 19), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_03459793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x03459793 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 52 : mword 6, Regidx (mword_of_int 11), Regidx (mword_of_int 15), SLLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_03461793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x03461793 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 52 : mword 6, Regidx (mword_of_int 12), Regidx (mword_of_int 15), SLLI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04c92483 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04c92483 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 76 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 9), false, 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_04f76463 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04f76463 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 72 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BLTU), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_05048513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x05048513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_050ab503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x050ab503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 21), Regidx (mword_of_int 10), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_054a9463 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x054a9463 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 72 : mword 13, Regidx (mword_of_int 20), Regidx (mword_of_int 21), BNE), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_06f48c63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x06f48c63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 120 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BEQ), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_085040ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x085040ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 18564 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_08c97063 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x08c97063 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 128 : mword 13, Regidx (mword_of_int 12), Regidx (mword_of_int 18), BGEU), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_08d72c23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x08d72c23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 152 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 14), 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_0c201737 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0c201737 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 49665 : mword 20, Regidx (mword_of_int 14), LUI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_16850513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x16850513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 360 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_1d250513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x1d250513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 466 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_1e250513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x1e250513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 482 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_27e000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x27e000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 638 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_2ae7bc23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x2ae7bc23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 696 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_386000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x386000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 902 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_3f648493 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x3f648493 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1014 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_54a50513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x54a50513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1354 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_54f000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x54f000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 3406 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_55178793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x55178793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1361 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_68a50513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x68a50513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1674 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_80060613 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x80060613 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 2048 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 12), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_825ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x825ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095140 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_847fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x847fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2086982 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_879ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x879ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095224 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_995fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x995fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091412 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_9e1fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x9e1fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2087392 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ac1fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xac1fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091712 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ad4fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xad4fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2085588 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_b16ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb16ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2093846 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ba5ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xba5ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096036 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_bf1fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xbf1fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2092016 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_c6678793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc6678793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3174 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ca5ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xca5ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096292 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_d57ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd57ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096470 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_dbbfe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xdbbfe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2092474 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_de843703 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xde843703 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3560 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 14), false, 8), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_df1ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xdf1ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096624 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_e17fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe17fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2088470 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_e1c42503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe1c42503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3612 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), false, 4), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_e48fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe48fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2082376 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ea0ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xea0ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2094752 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ea9fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xea9fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2084520 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_ec0791e3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xec0791e3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 7874 : mword 13, zreg, Regidx (mword_of_int 15), BNE), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f15ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf15ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096916 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f6dfd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf6dfd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2088812 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f8648493 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf8648493 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3974 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_f89ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf89ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2097032 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fc250513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfc250513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 4034 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fcafd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfcafd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2086858 : mword 21, Regidx (mword_of_int 1)), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fd040513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfd040513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 4048 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), ADDI), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fe0a80e3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfe0a80e3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8160 : mword 13, zreg, Regidx (mword_of_int 21), BEQ), s).
Proof. decode_bridge_ms. Qed.

Lemma kd_fee49ce3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfee49ce3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8184 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 9), BNE), s).
Proof. decode_bridge_ms. Qed.

