(* ====================================================================== *)
(* ResvAxioms.v -- THE LR/SC RESERVATION PLATFORM HOOKS, AT THE *TERM*      *)
(* LEVEL.                                                                  *)
(*                                                                         *)
(* [load_reservation] and [cancel_reservation] are declared by the         *)
(* generated model as opaque *Axioms* (rv64d.v:21793,21802): the LR/SC     *)
(* reservation set is platform state, outside [regstate] / [mstate], so    *)
(* the model does not give them a body.  Every proof that steps an         *)
(* [lr]/[sc]/[amo] instruction -- and [reset_sys], which cancels the        *)
(* reservation on power-on -- has to say something about them.             *)
(*                                                                         *)
(* WHY THE ASSUMPTION MUST BE AT THE TERM LEVEL, AND NOT AT [exec].        *)
(* The obvious (and, until this file, the actual) shape was an assumption  *)
(* about the *interpreter's answer*:                                       *)
(*                                                                         *)
(*   Axiom exec_load_reservation : exec (load_reservation a w) s = Some (tt, s).   *)
(*                                                                         *)
(* That is enough while a hart steps a WHOLE CYCLE at a time -- the only    *)
(* thing anyone asks of the hook is what [exec] returns for it.  It is NOT  *)
(* enough under per-node stepping (design/main-cycle-port.md): the language *)
(* steps one monad NODE at a time and [RiscvLang.mnode_step] matches on the *)
(* monad's CONSTRUCTORS, so an application of an opaque constant has no arm *)
(* at all and the configuration is IRREDUCIBLE.  Adequacy is [NotStuck] and *)
(* arbitrary user code may execute [lr]/[sc], so an exec-level assumption   *)
(* would leave a genuine SAFETY HOLE -- not an inconvenience -- in the      *)
(* user tier.  An assumption about the TERM tells every consumer (the       *)
(* machine, [exec], the footprint walkers [goodb]/[goodmb]/[hfrun]/[hmrun]) *)
(* the same thing at once: the hook IS [returnm tt], which every one of     *)
(* them can step.                                                          *)
(*                                                                         *)
(* IT IS STRICTLY A REFINEMENT of what was assumed before: the realisation  *)
(* [load_reservation := fun _ _ => returnm tt], [cancel_reservation :=      *)
(* fun _ => returnm tt] satisfies both axioms here, and both of the old     *)
(* exec-level axioms follow from these in one line (see                     *)
(* [UserMemAccess.exec_load_reservation] / [_cancel_reservation], which are  *)
(* kept as corollaries so no consumer's proof moves).  So the tree's axiom  *)
(* count is unchanged: two [exec]-level assumptions are replaced by two     *)
(* term-level ones that imply them.                                        *)
(*                                                                         *)
(* WHAT IS *NOT* ASSUMED.  Nothing about the reservation's CONTENT:         *)
(* [match_reservation] and [valid_reservation] stay opaque [bool] axioms of *)
(* the model and are destructed both ways wherever an SC or a wake-up       *)
(* decision reads them.  Only the two [M unit]-valued hooks, whose whole    *)
(* observable effect on the modelled architectural state (sregs / mem /     *)
(* mdev) is nil, are pinned here.                                          *)
(*                                                                         *)
(* THE OTHER OPAQUE [M]-VALUED MODEL AXIOMS are [get_16_random_bits] (the   *)
(* Zkr seed CSR, illegal at U) and [plat_term_read]/[plat_term_write] (HTIF,*)
(* dead under the [htif_tohost_base = None] premise).  They are deliberately*)
(* NOT pinned here: nothing in the tree needs to step one, and a hart that   *)
(* reaches one should get stuck loudly rather than quietly.                 *)
(*                                                                         *)
(* This file requires nothing but the generated model, so it can sit below  *)
(* the language file and be shared by the boot cone and the U-mode tier.    *)
(* IMPORT ORDER TRAP (as in ArchReset.v): [SailStdpp.Base] re-exports       *)
(* Prompt_monad's [read_reg]/[write_reg], so [Import Defs] must come LAST.  *)
(* ====================================================================== *)
From Stdlib Require Import ZArith.
Require Import SailStdpp.Base.
Require Import Riscv.rv64d_types Riscv.rv64d.
Import Defs.

Axiom load_reservation_term :
  forall (a : mword (if 64 =? 32 then 34 else 64)) (n : Z),
    load_reservation a n = Defs.returnm tt.

Axiom cancel_reservation_term :
  forall (u : unit), cancel_reservation u = Defs.returnm tt.
