(* ====================================================================== *)
(* SystemAssumptions.v -- THE ASSUMPTION AUDIT of the system theorem.      *)
(*                                                                        *)
(* [Print Assumptions] on [SystemAdequacy.xv6_power_adequacy_xv6Σ]: the    *)
(* one check that sees through every functor and every seal, and so the    *)
(* only thing that can tell you what the system theorem actually rests on. *)
(* Expect the five Sail platform externs ([load_reservation],              *)
(* [cancel_reservation], [match_reservation], [valid_reservation],         *)
(* [plat_term_write]), [functional_extensionality_dep], and the            *)
(* deliberately-unproven kernel functions.  ANYTHING ELSE IS A REGRESSION  *)
(* (xv6-bump-playbook.md §7.2).                                            *)
(*                                                                        *)
(* WHY IT IS A FILE OF ITS OWN, AND ONE [iris/_CoqProject] DOES NOT LIST.  *)
(* The statement measured 95 s of SystemAdequacy.v's 98.6 s -- the same    *)
(* file is 3.6 s without it -- and it sits on the strictly serial build    *)
(* tail, so it was ~30 % of a clean build's wall clock, paid by every      *)
(* developer on every build.  It is not incidental cost: the command walks *)
(* every opaque proof term in the transitive cone, re-cooking each one     *)
(* out of its section and re-substituting it through its functor as it     *)
(* goes.  claude-notes/optimization.md has the measurements.               *)
(*                                                                        *)
(* So the audit is compiled by `make audit` instead, and by CI after the   *)
(* build (the output lands in the run's step summary).  The commented row  *)
(* in [iris/_CoqProject] is what tells the coverage checker this file is   *)
(* out of the coq_makefile build on purpose rather than by accident.       *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions].  Consecutive calls share NOTHING --  *)
(* measured back to back in one process, 94.5 s then 100.6 s -- so a       *)
(* second audit here does not ride along on the first, it doubles the      *)
(* bill.  If [xv6_fs_adequacy_xv6Σ] ever needs auditing too, that is a     *)
(* deliberate ~2x, not a free addition.                                    *)
(* ====================================================================== *)
Require Import SystemAdequacy.

Print Assumptions xv6_power_adequacy_xv6Σ.
