(* ====================================================================== *)
(* UnionAssumptions.v -- THE ASSUMPTION AUDIT of the UNION APPLICATION's   *)
(* top theorem.                                                            *)
(*                                                                        *)
(* [Print Assumptions] on [UInitUnion.union_adequacy_closed]: safety of    *)
(* the whole machine plus the console trace property for the application  *)
(* of claude-notes/design/union.md -- the user types lines of the shapes   *)
(* `echo ws', `echo ws > f', `cat f', and `p | F1 | ... | Fn' for a      *)
(* producer `echo ws' or `cat f' and filter stages `cat' or `grep w' (w   *)
(* one alphanumeric word) at the console of an unmodified xv6, the        *)
(* machine is power-cycled at will, and each cycle's output is a prefix   *)
(* of the transcript its input calls for from the cycle's boot state.     *)
(* The claim is born at the union model [UnionDisc.ulmG].                 *)
(*                                                                        *)
(* WHY A SEPARATE FILE beside [SystemAssumptions.v] and                    *)
(* [TreeAssumptions.v]: no two of the cones contain each other.  The       *)
(* system theorem is the chain at the TRIVIAL application and names no     *)
(* user program; this one walks the whole [Uk*]/[USh*]/[UInit*] program    *)
(* tier and the union stage ([UnionDisc]/[UnionOut]/[UnionLinks]/         *)
(* [AppUnionRec]).  A grep for [Axiom] and [Admitted] cannot see a sealed  *)
(* [Spec*] module [Parameter]; [Print Assumptions] is the check that does. *)
(*                                                                        *)
(* EXPECT EXACTLY FOURTEEN, and the split matters:                         *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  11  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*      ([PrimString.string]/[.get]/[.cat]/[.length], [PrimInt63.int]/     *)
(*      [.eqb]/[.sub]/[.lsl]/[.lsr]/[.land]/[.lor])                        *)
(*                                                                        *)
(* THAT IS THE SYSTEM THEOREM'S THIRTEEN PLUS [PrimString.length], the     *)
(* byte-count every hex-imported binary blob is decoded by                 *)
(* ([PStringBytes.pstring_hex_length]).  ANYTHING ELSE -- and in           *)
(* particular any [Spec*]/[Link*] module [Parameter] -- IS A REGRESSION.   *)
(* The theorem's binder list is the complementary check (a premise never   *)
(* appears here); it holds three hardware facts about the initial state    *)
(* and nothing else.                                                       *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its siblings: [Print       *)
(* Assumptions] re-cooks every opaque proof term in the transitive cone.   *)
(* Compiled by `make audit-union` / `make audit-union-only` and by CI; the *)
(* commented row in [iris/_CoqProject] tells the coverage checker the file *)
(* is out of the build ON PURPOSE.  ONE print: consecutive calls share     *)
(* nothing.                                                                *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is [UnionOutPure.union_phi],       *)
(* [LineModel.v]'s [lm_disc] and [lm_good_out], and [UnionDisc.v]'s model  *)
(* [ulmG] over [FileDisc.v] and [PipesDisc.v]: they ARE the specification. *)
(* ====================================================================== *)
Require Import UInitUnion.

Print Assumptions union_adequacy_closed.

(* ---- FRONTIER (cut W0 of claude-notes/design/filenames.md; removed at
   W4, when the model's name class becomes [FileName.txt_name] and the
   laws enter the anchor's cone).  The widened class's law bundle: L1-L4
   of [FileName.name_laws] at [txt_name], L4 by one computation over the
   image's root block.  Its axioms must lie within the fourteen above. *)
Require Import FileName.

Print Assumptions txt_laws.
