#!/usr/bin/env python3
"""Generate a self-contained Iris proofmode benchmark.

The proof holds N hypotheses in the spatial context and then performs M
proofmode steps that do not change the context (intro one premise, clear it).
Every step's proof term embeds the whole environment, so the file prices
`|context| x steps` -- and by varying only the LENGTH of the N hypothesis
names, it prices the `ident` representation alone.

Usage: gen.py <out.v> <N> <M> <namelen|anon>
"""
import sys

out, N, M, mode = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]

if mode == 'anon':
    intro = ' '.join(['?'] * N)
    tag = 'anonymous (IAnon)'
else:
    L = int(mode)
    # distinct names of exactly length L
    names = []
    for i in range(N):
        suffix = str(i)
        base = 'H' + 'x' * max(0, L - 1 - len(suffix)) + suffix
        names.append(base[:L] if len(base) >= L else base)
    intro = ' '.join(names)
    tag = 'named, length %d' % L

src = '''(* GENERATED by gen.py -- Iris proofmode ident-representation benchmark.
   N = %d hypotheses, M = %d steps, %s *)
From iris.base_logic.lib Require Import iprop.
From iris.proofmode Require Import proofmode.

Section bench.
  Context {Sigma : gFunctors}.

  Lemma bench (P : iProp Sigma) :
%s
    True.
  Proof.
    iIntros "%s".
    do %d (iIntros "z"; iClear "z").
    by iPureIntro.
  Qed.
End bench.
''' % (N, M, tag,
       '\n'.join(['    P -∗'] * (N + M)),
       intro, M)
open(out, 'w').write(src.replace('Sigma', 'Σ'))
print('%s: N=%d M=%d %s' % (out, N, M, tag))
