(* ClintMsipJh7110Pass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [clint_msip] on platform [jh7110].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
Require Import VRun ClintMsipJh7110Run.

Module ClintMsipJh7110Pass <: TEST_PASSES ClintMsipJh7110.
  Lemma passes : run_passes ClintMsipJh7110.observed ClintMsipJh7110.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End ClintMsipJh7110Pass.
