(* ConcSbQemuPass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [conc_sb] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
Require Import VRun ConcSbQemuRun.

Module ConcSbQemuPass <: TEST_PASSES ConcSbQemu.
  Lemma passes : run_passes ConcSbQemu.observed ConcSbQemu.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End ConcSbQemuPass.
