(* CoreIcacheQemuPass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [core_icache] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
Require Import VRun CoreIcacheQemuRun.

Module CoreIcacheQemuPass <: TEST_PASSES CoreIcacheQemu.
  Lemma passes : run_passes CoreIcacheQemu.observed CoreIcacheQemu.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End CoreIcacheQemuPass.
