(* CoreIcacheJh7110Pass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [core_icache] on platform [jh7110].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
Require Import VRun CoreIcacheJh7110Run.

Module CoreIcacheJh7110Pass <: TEST_PASSES CoreIcacheJh7110.
  Lemma passes : run_passes CoreIcacheJh7110.observed CoreIcacheJh7110.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End CoreIcacheJh7110Pass.
