#!/bin/sh
# tcb-report.sh [<fully.qualified.Theorem>]
#
# The DEFINITION-LEVEL trusted base of the adequacy theorem's STATEMENT:
# which files a reader must read, and how many lines of them.
#
# [Print Assumptions] answers "what does this PROOF assume".  This answers
# the other half: Rocq's kernel checks the proof, so nothing a proof
# mentions needs trusting -- but the STATEMENT is the thing a human agrees
# to, so every definition it unfolds to is trusted.
#
# THE WHOLE TRICK IS THE SEED, and it is the only idea here.  Pointing
# [Print All Dependencies] at the THEOREM walks its proof cone -- the
# untrusted half, thousands of files.  Pointing it at a DEFINITION WHOSE
# BODY IS THE STATEMENT walks the statement instead.  That is the
# [Definition tcb_seed := ltac:(... type of ...)] line below.
#
# WHAT IT OVER-APPROXIMATES.  assumptions.ml's traversal forces opaque proof
# bodies and walks into them, so definitions reached only through a [Qed]
# are reported too.  MEASURED on xv6_fs_adequacy_xv6Σ (2026-08-27): the
# constant count inflates from 3055 to 3745, but every extra one lands
# OUTSIDE this tree -- 40 external files, all lia/ring/setoid-rewriting
# residue left behind in [RiscvLang.riscv_lang_mixin]'s proof (Ring_theory,
# Ring_polynom, micromega/*, Setoids/Setoid, ssr/ssreflect,
# ClassicalDedekindReals, ...).  The IN-TREE answer is exact, which is why
# this is a ten-line script and not a custom traversal.  If that ever stops
# being true -- a statement-level definition picking up a [Qed] from a
# Wp*/Code* file -- the in-tree file count jumps, which is the signal.
#
# Run from the project root, against an already-built tree.  ~3 s.
set -e
SWITCH=${SWITCH:-/shared/xv6rocq}
RUN=${RUN:-opam exec --switch=$SWITCH --}
root=$(cd "$(dirname "$0")/../.." && pwd)
here=$root/tools/tcb
target=${1:-xv6iris.FsAdequacyImg.xv6_fs_adequacy_xv6Σ}
flags=$(sed -n 's/^-arg //p;/^-[RQ] /p' "$root/iris/_CoqProject" | tr '\n' ' ')

cat > "$here/TcbSeed.v" <<ROCQ
(* Generated by tools/tcb/tcb-report.sh.  Nothing in any _CoqProject builds
   this, so it is invisible to the build and to the dead-import sweep. *)
Require Import ${target%.*}.
Definition tcb_seed := ltac:(let T := type of (@$target) in exact T).
Set Printing Width 300.
Print All Dependencies tcb_seed.
Print Assumptions tcb_seed.
ROCQ

cd "$root/iris"
$RUN coqc $flags -noglob "$here/TcbSeed.v"
