#!/usr/bin/env python3
"""Dump the xv6 kernel ELF's text section into Lean data (Xv6/KernelImage.lean).

Each instruction becomes a triple (address, width in bytes, encoding), where the
encoding is exactly the integer the Sail decoder is given (the little-endian
assembled instruction word), so no byte swapping is needed on the Lean side.
Symbols are emitted as `KernelSyms.<name> : Nat`.

Usage: tools/dump_kernel.py [--kernel PATH] [--out PATH] [--objdump OBJDUMP]
"""
import argparse, os, re, subprocess, sys

INSTR_RE = re.compile(r'^\s*([0-9a-f]+):\t([0-9a-f ]+?)\s*(?:\t(.*))?$')
SYM_RE = re.compile(r'^\s*([0-9a-f]+) <([A-Za-z0-9_.$]+)>:$')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--kernel', default='xv6-riscv/kernel/kernel')
    ap.add_argument('--out', default='Xv6/KernelImage.lean')
    ap.add_argument('--objdump', default='riscv64-linux-gnu-objdump')
    ap.add_argument('--chunk', type=int, default=500)
    a = ap.parse_args()

    out = subprocess.run([a.objdump, '-d', '--section=.text', a.kernel],
                         check=True, capture_output=True, text=True).stdout
    instrs, syms = [], []
    for line in out.splitlines():
        m = SYM_RE.match(line)
        if m:
            syms.append((m.group(2), int(m.group(1), 16)))
            continue
        m = INSTR_RE.match(line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        words = m.group(2).split()
        # objdump prints one field per instruction (the assembled word)
        for w in words:
            width = len(w) // 2
            instrs.append((addr, width, int(w, 16), (m.group(3) or '').strip()))
            addr += width

    with open(a.out, 'w') as f:
        rev = subprocess.run(['git', '-C', os.path.dirname(os.path.dirname(os.path.abspath(a.kernel))),
                              'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip() or 'unknown'
        f.write('-- AUTO-GENERATED by tools/dump_kernel.py from %s (xv6-riscv %s); do not edit.\n' % (os.path.basename(a.kernel), rev))
        f.write('-- The xv6 kernel text section: (address, width in bytes, instruction word).\n')
        f.write('namespace Xv6.Kernel\n\n')
        f.write('/-- One instruction of the kernel text. -/\n')
        f.write('structure KInstr where\n  addr : Nat\n  width : Nat\n  enc : Nat\n  deriving Repr, DecidableEq\n\n')
        chunks = [instrs[i:i+a.chunk] for i in range(0, len(instrs), a.chunk)]
        for ci, ch in enumerate(chunks):
            f.write('def textChunk%d : List KInstr := [\n' % ci)
            f.write(',\n'.join('  -- %s\n  ⟨0x%x, %d, 0x%0*x⟩' % (asm.replace('\n', ' '), ad, w, 2*w, e) for ad, w, e, asm in ch))
            f.write('\n]\n\n')
        f.write('/-- All %d instructions of the kernel text, in address order. -/\n' % len(instrs))
        f.write('def text : List KInstr :=\n  ' + ' ++ '.join('textChunk%d' % i for i in range(len(chunks))) + '\n\n')
        f.write('end Xv6.Kernel\n\nnamespace MachCSL.KernelSyms\n\n')
        seen = set()
        for name, addr in syms:
            lean = name.replace('.', '_').replace('$', '_')
            if lean in seen or not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', lean):
                continue
            seen.add(lean)
            f.write('def %s : Nat := 0x%x\n' % ('«%s»' % lean, addr))
        f.write('\nend MachCSL.KernelSyms\n')
    print('wrote %s: %d instructions, %d symbols' % (a.out, len(instrs), len(seen)), file=sys.stderr)
    # The search-tree form proofs look instructions up in (KernelText.lean proves it equal).
    subprocess.check_call([os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen_text_tree.py'),
                           '--image', a.out, '--out', os.path.join(os.path.dirname(a.out), 'KernelTree.lean')])

if __name__ == '__main__':
    main()
