(* QEMU/ConcBytePass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [conc_byte] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.QEMU Require Import ConcByteRun.

Module ConcBytePass <: TEST_PASSES ConcByte.
  Lemma passes : run_passes ConcByte.observed ConcByte.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End ConcBytePass.
