(* QEMU/CoreCsrwidePass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [core_csrwide] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.QEMU Require Import CoreCsrwideRun.

Module CoreCsrwidePass <: TEST_PASSES CoreCsrwide.
  Lemma passes : run_passes CoreCsrwide.observed CoreCsrwide.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End CoreCsrwidePass.
