(* QEMU/DiskIdentShmselPass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [disk_ident_shmsel] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.QEMU Require Import DiskIdentShmselRun.

Module DiskIdentShmselPass <: TEST_PASSES DiskIdentShmsel.
  Lemma passes : run_passes DiskIdentShmsel.observed DiskIdentShmsel.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End DiskIdentShmselPass.
