(* QEMU/DiskOrderPass.v -- GENERATED by tools/vtest.  Do not edit.

   The proof for the run of case [disk_order] on platform [qemu].  What is proved
   is a statement about [RiscvLang.prim_step]; [VExecStep] is what carries a
   computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.QEMU Require Import DiskOrderTest DiskOrderRun.

Module DiskOrderPass <: TEST_PASSES_AGREE DiskOrder DiskOrderRun.
  Lemma agrees :
    run_agrees DiskOrder.hart DiskOrder.text DiskOrder.regions
               DiskOrder.uart_input DiskOrder.disk_init DiskOrderRun.observed.
  Proof.
    intros o Ho.
    cbn [DiskOrderRun.observed DiskOrderRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 30000);
              vm_compute; repeat split |]).
    destruct Ho.
  Qed.
End DiskOrderPass.
