(* QEMU/DiskIdentFeatselPass.v -- GENERATED by tools/vtest.  Do not edit.
   VERDICT: agree

   The proof for the run of case [disk_ident_featsel] on platform [qemu].  The theorem is
   [VRun.run_passes], a statement about [RiscvLang.prim_step]; [VExecStep]
   is what carries a computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.QEMU Require Import DiskIdentFeatselTest DiskIdentFeatselRun.

Module DiskIdentFeatselPass <: TEST_PASSES DiskIdentFeatsel DiskIdentFeatselRun.
  Lemma passes :
    run_passes DiskIdentFeatsel.hart DiskIdentFeatsel.text DiskIdentFeatsel.regions
               DiskIdentFeatsel.uart_input DiskIdentFeatsel.disk_init DiskIdentFeatselRun.observed.
  Proof.
    left. intros o Ho.
    cbn [DiskIdentFeatselRun.observed DiskIdentFeatselRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 2000);
              vm_compute; repeat split |]).
    destruct Ho.
  Qed.
End DiskIdentFeatselPass.
