(* QEMU/PtAdPass.v -- GENERATED by tools/vtest.  Do not edit.

   The passing proof for the run of case [pt_ad] on platform [qemu].
   The theorem is [VRun.TEST_PASSES], stated once and parametric in the
   run; this is its instantiation. *)
From Stdlib Require Import List ZArith.
From VTest Require Import VRun.
From VTest.QEMU Require Import PtAdRun.

Module PtAdPass <: TEST_PASSES PtAd.
  Lemma passes : run_passes PtAd.observed PtAd.outcome.
  Proof. apply run_passes_b_sound. vm_cast_no_check (eq_refl true). Qed.
End PtAdPass.
